# Generated by Django 3.0.3 on 2020-04-28 20:54

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_auto_20200427_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
