# Generated by Django 3.0.3 on 2020-05-02 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0009_auto_20200502_1911'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
